# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'

development:
  adapter: postgresql
  database: imdb_development
  encoding: utf8
  pool: 5
  timeout: 5000
  username: postgres             
  password: 

test:
  adapter: postgresql
  database: imdb_test
  encoding: utf8
  pool: 5
  timeout: 5000
  username: postgres             
  password: 
  
production:
  adapter: postgresql
  database: imdb_production
  encoding: utf8
  pool: 5
  timeout: 5000
  username: postgres             
  password: 
